パリンドローム
Aさんは回文が大好きで、回文を含む文字列をいつも探しています。ある時、円周率は無限数列だから 多くの回文を含むことに気づき、膨大な数の組み合わせから回文を探してみたいと思うようになりました。 人力で調べるのは不可能なので、数列を受け取って回文となっている最長部分の数列を出力するプログラムを書くことにしました。
ザ・ミッション
入力された数字のうち最長の回文になっている部分を表示するプログラムを作ってください。
回文とは?
ある文字列Aが回文であるとは、引数の文字列を逆順にならべかえた文字列を出力する関数をreverse()とした時に、
A == reverse(A)
となることを言います。例えば1や22、1234321などは回文です。
実装の詳細
CLI
引数を受け取り、結果を標準出力に出力するCLIアプリケーションとして解答を実装してください。 詳細は末尾の「CLI アプリ作成用テンプレート」を参照ください。
入力ルール
* CLIアプリケーションには引数が 1  1 つ与えられます。
* 引数はファイルのパスを表します。
* ファイルには 0  0 以上 9  9 以下で構成された文字列が書かれています。
* ファイルに書かれている文字列の長さは、 100  100 万文字以下です。
出力ルール
* 引数で与えられたファイル中の文字列の中で、最長の回文となっている部分文字列を出力します。
* 最長の回文が複数ある場合、文字列内で最初に出現する最長の回文を出力します。
入出力例
$ ./[YOUR APP] ./test/basic_testcase01.txt
上記のコマンドで与えられたファイルbasic_testcase01.txtの中身が以下だった場合
12343215467
出力は以下のようになります。
1234321
なお、期待する入出力は test/ ディレクトリにいくつか定義されています。 実装する際の参考にしてください。

CLIアプリケーション作成方法 (Ruby)
main.rbを編集して、CLIアプリを実装してください。 チャレンジ内でファイルの作成が許可されていれば、可読性等のためにファイルを分割する事も可能です。
コマンドライン引数の取得方法
main.rb内で定義されている、mainという関数から、 argv の名前で取得可能です。
def main(argv)
  # code to run
end
ここでの argv は ARGV の内容がそのまま渡されます。
コマンド実行結果の標準出力への出力
stdout への出力は標準の puts メソッド等が使用可能です
puts "Hello World"
外部ライブラリの追加方法
外部ライブラリを使用する場合は以下の手順で実施してください。
* Gemfileにライブラリ名を記述


not ok 1 文字長が奇数の回文を求められる
  AssertionError: 1番目のデータが違います。
  期待された答え: 121
  あなたの答え: txt
  #### 入力:
  121


  #### あなたの答え:
  txt

  #### 期待された答え:
  121
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 2 文字長が偶数の回文を求められる
  AssertionError: 1番目のデータが違います。
  期待された答え: 1221
  あなたの答え: txt
  #### 入力:
  1221


  #### あなたの答え:
  txt

  #### 期待された答え:
  1221
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 3 回文が複数ある場合、最長の回文が出力される
  AssertionError: 1番目のデータが違います。
  期待された答え: 68088588086
  あなたの答え: txt
  #### 入力:
  33368088588086


  #### あなたの答え:
  txt

  #### 期待された答え:
  68088588086
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される
  AssertionError: 1番目のデータが違います。
  期待された答え: 1221
  あなたの答え: txt
  #### 入力:
  12214334


  #### あなたの答え:
  txt

  #### 期待された答え:
  1221
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
  AssertionError: 1番目のデータが違います。
  期待された答え: 33433
  あなたの答え: txt
  #### 入力:
  43343321


  #### あなたの答え:
  txt

  #### 期待された答え:
  33433
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 6 比較的長い文字列でも回文が出力できる
  AssertionError: 1番目のデータが違います。
  期待された答え: 012343210
  あなたの答え: txt
  #### 入力:
  123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...

  #### あなたの答え:
  txt

  #### 期待された答え:
  012343210
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 7 自然定数の底から回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 68088588086
  あなたの答え: txt
  #### 入力:
  271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...

  #### あなたの答え:
  txt

  #### 期待された答え:
  68088588086
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 8 単一桁の長い繰り返しから回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
  あなたの答え: txt
  #### 入力:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...

  #### あなたの答え:
  txt

  #### 期待された答え:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 9 長い回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
  あなたの答え: txt
  #### 入力:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...

  #### あなたの答え:
  txt

  #### 期待された答え:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 10 長い回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 433629512303688918622245334416679134207460948732594038763304981107729497481564735150126456075107079238909155720556580228025755484607697524206353121345159827595957918671191948570817622516287902696773804121998179834217935855134704284896105025108539245022555246686298108620363218362086234078859488490375...
  あなたの答え: txt
  #### 入力:
  439671913169768210880962528779044921214653729760961967312219315729051436700988975291224467598181008351941131051570812459210249369106411836951001002340483417565507341626341463773029280521487959984058684941220744882834172187098695773189403499087280909110119181670989031493301341331552586696953063188448...

  #### あなたの答え:
  txt

  #### 期待された答え:
  433629512303688918622245334416679134207460948732594038763304981107729497481564735150126456075107079238909155720556580228025755484607697524206353121345159827595957918671191948570817622516287902696773804121998179834217935855134704284896105025108539245022555246686298108620363218362086234078859488490375...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>
# tests 10
# pass 0
# fail 10
exit_code = 10, reason = DONE
bundle install
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/usr/local/bundle`
mocha --exit -R tap
1..10

#### 入力:
121

#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 1 文字長が奇数の回文を求められる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
1221

#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 2 文字長が偶数の回文を求められる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
33368088588086

#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 3 回文が複数ある場合、最長の回文が出力される
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
12214334

#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
43343321

#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...
#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 6 比較的長い文字列でも回文が出力できる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...
#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 7 自然定数の底から回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 8 単一桁の長い繰り返しから回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 9 長い回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
439671913169768210880962528779044921214653729760961967312219315729051436700988975291224467598181008351941131051570812459210249369106411836951001002340483417565507341626341463773029280521487959984058684941220744882834172187098695773189403499087280909110119181670989031493301341331552586696953063188448...
#### 標準エラー出力:
main.rb:6:in `get_palindrome': undefined method `size' for nil:NilClass (NoMethodError)
	from main.rb:2:in `main'
	from main.rb:14:in `<main>'

not ok 10 長い回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
# tests 10
# pass 0
# fail 10
exit_code = 10, reason = DONE
bundle install
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/usr/local/bundle`
mocha --exit -R tap
1..10

not ok 1 文字長が奇数の回文を求められる
  AssertionError: 1番目のデータが違います。
  期待された答え: 121
  あなたの答え: 0
  #### 入力:
  121


  #### あなたの答え:
  0

  #### 期待された答え:
  121
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 2 文字長が偶数の回文を求められる
  AssertionError: 1番目のデータが違います。
  期待された答え: 1221
  あなたの答え: 0
  #### 入力:
  1221


  #### あなたの答え:
  0

  #### 期待された答え:
  1221
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 3 回文が複数ある場合、最長の回文が出力される
  AssertionError: 1番目のデータが違います。
  期待された答え: 68088588086
  あなたの答え: 0
  #### 入力:
  33368088588086


  #### あなたの答え:
  0

  #### 期待された答え:
  68088588086
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される
  AssertionError: 1番目のデータが違います。
  期待された答え: 1221
  あなたの答え: 0
  #### 入力:
  12214334


  #### あなたの答え:
  0

  #### 期待された答え:
  1221
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
  AssertionError: 1番目のデータが違います。
  期待された答え: 33433
  あなたの答え: 0
  #### 入力:
  43343321


  #### あなたの答え:
  0

  #### 期待された答え:
  33433
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 6 比較的長い文字列でも回文が出力できる
  AssertionError: 1番目のデータが違います。
  期待された答え: 012343210
  あなたの答え: 0
  #### 入力:
  123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...

  #### あなたの答え:
  0

  #### 期待された答え:
  012343210
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 7 自然定数の底から回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 68088588086
  あなたの答え: 0
  #### 入力:
  271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...

  #### あなたの答え:
  0

  #### 期待された答え:
  68088588086
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 8 単一桁の長い繰り返しから回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
  あなたの答え: 0
  #### 入力:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...

  #### あなたの答え:
  0

  #### 期待された答え:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 9 長い回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
  あなたの答え: 0
  #### 入力:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...

  #### あなたの答え:
  0

  #### 期待された答え:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 10 長い回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 433629512303688918622245334416679134207460948732594038763304981107729497481564735150126456075107079238909155720556580228025755484607697524206353121345159827595957918671191948570817622516287902696773804121998179834217935855134704284896105025108539245022555246686298108620363218362086234078859488490375...
  あなたの答え: 0
  #### 入力:
  439671913169768210880962528779044921214653729760961967312219315729051436700988975291224467598181008351941131051570812459210249369106411836951001002340483417565507341626341463773029280521487959984058684941220744882834172187098695773189403499087280909110119181670989031493301341331552586696953063188448...

  #### あなたの答え:
  0

  #### 期待された答え:
  433629512303688918622245334416679134207460948732594038763304981107729497481564735150126456075107079238909155720556580228025755484607697524206353121345159827595957918671191948570817622516287902696773804121998179834217935855134704284896105025108539245022555246686298108620363218362086234078859488490375...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>
# tests 10
# pass 0
# fail 10
exit_code = 10, reason = DONE
bundle install
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/usr/local/bundle`
mocha --exit -R tap
1..10

not ok 1 文字長が奇数の回文を求められる
  AssertionError: 1番目のデータが違います。
  期待された答え: 121
  あなたの答え: ./test/in/basic/basic_testcase01.txt
  #### 入力:
  121


  #### あなたの答え:
  ./test/in/basic/basic_testcase01.txt

  #### 期待された答え:
  121
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 2 文字長が偶数の回文を求められる
  AssertionError: 1番目のデータが違います。
  期待された答え: 1221
  あなたの答え: ./test/in/basic/basic_testcase02.txt
  #### 入力:
  1221


  #### あなたの答え:
  ./test/in/basic/basic_testcase02.txt

  #### 期待された答え:
  1221
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 3 回文が複数ある場合、最長の回文が出力される
  AssertionError: 1番目のデータが違います。
  期待された答え: 68088588086
  あなたの答え: ./test/in/basic/basic_testcase03.txt
  #### 入力:
  33368088588086


  #### あなたの答え:
  ./test/in/basic/basic_testcase03.txt

  #### 期待された答え:
  68088588086
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される
  AssertionError: 1番目のデータが違います。
  期待された答え: 1221
  あなたの答え: ./test/in/basic/basic_testcase04.txt
  #### 入力:
  12214334


  #### あなたの答え:
  ./test/in/basic/basic_testcase04.txt

  #### 期待された答え:
  1221
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
  AssertionError: 1番目のデータが違います。
  期待された答え: 33433
  あなたの答え: ./test/in/basic/basic_testcase05.txt
  #### 入力:
  43343321


  #### あなたの答え:
  ./test/in/basic/basic_testcase05.txt

  #### 期待された答え:
  33433
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 6 比較的長い文字列でも回文が出力できる
  AssertionError: 1番目のデータが違います。
  期待された答え: 012343210
  あなたの答え: ./test/in/basic/basic_testcase06.txt
  #### 入力:
  123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...

  #### あなたの答え:
  ./test/in/basic/basic_testcase06.txt

  #### 期待された答え:
  012343210
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 7 自然定数の底から回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 68088588086
  あなたの答え: ./test/in/basic/basic_testcase07.txt
  #### 入力:
  271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...

  #### あなたの答え:
  ./test/in/basic/basic_testcase07.txt

  #### 期待された答え:
  68088588086
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 8 単一桁の長い繰り返しから回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
  あなたの答え: ./test/in/basic/basic_testcase08.txt
  #### 入力:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...

  #### あなたの答え:
  ./test/in/basic/basic_testcase08.txt

  #### 期待された答え:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 9 長い回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
  あなたの答え: ./test/in/basic/basic_testcase09.txt
  #### 入力:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...

  #### あなたの答え:
  ./test/in/basic/basic_testcase09.txt

  #### 期待された答え:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>

not ok 10 長い回文を見つけられる
  AssertionError: 1番目のデータが違います。
  期待された答え: 433629512303688918622245334416679134207460948732594038763304981107729497481564735150126456075107079238909155720556580228025755484607697524206353121345159827595957918671191948570817622516287902696773804121998179834217935855134704284896105025108539245022555246686298108620363218362086234078859488490375...
  あなたの答え: ./test/in/basic/basic_testcase10.txt
  #### 入力:
  439671913169768210880962528779044921214653729760961967312219315729051436700988975291224467598181008351941131051570812459210249369106411836951001002340483417565507341626341463773029280521487959984058684941220744882834172187098695773189403499087280909110119181670989031493301341331552586696953063188448...

  #### あなたの答え:
  ./test/in/basic/basic_testcase10.txt

  #### 期待された答え:
  433629512303688918622245334416679134207460948732594038763304981107729497481564735150126456075107079238909155720556580228025755484607697524206353121345159827595957918671191948570817622516287902696773804121998179834217935855134704284896105025108539245022555246686298108620363218362086234078859488490375...
  : expected 0 to equal 1
      at Context.it (test/test_runner.js:87:31)
      at <anonymous>
# tests 10
# pass 0
# fail 10
exit_code = 10, reason = DONE
bundle install
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/usr/local/bundle`
mocha --exit -R tap
1..10

#### 入力:
121

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 1 文字長が奇数の回文を求められる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
1221

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 2 文字長が偶数の回文を求められる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
33368088588086

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 3 回文が複数ある場合、最長の回文が出力される
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
12214334

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
43343321

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 6 比較的長い文字列でも回文が出力できる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 7 自然定数の底から回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 8 単一桁の長い繰り返しから回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 9 長い回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
439671913169768210880962528779044921214653729760961967312219315729051436700988975291224467598181008351941131051570812459210249369106411836951001002340483417565507341626341463773029280521487959984058684941220744882834172187098695773189403499087280909110119181670989031493301341331552586696953063188448...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:17:in `<main>'

not ok 10 長い回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
# tests 10
# pass 0
# fail 10
exit_code = 10, reason = DONE
bundle install
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/usr/local/bundle`
mocha --exit -R tap
1..10

#### 入力:
121

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 1 文字長が奇数の回文を求められる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
1221

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 2 文字長が偶数の回文を求められる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
33368088588086

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 3 回文が複数ある場合、最長の回文が出力される
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
12214334

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
43343321

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 6 比較的長い文字列でも回文が出力できる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 7 自然定数の底から回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 8 単一桁の長い繰り返しから回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 9 長い回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
439671913169768210880962528779044921214653729760961967312219315729051436700988975291224467598181008351941131051570812459210249369106411836951001002340483417565507341626341463773029280521487959984058684941220744882834172187098695773189403499087280909110119181670989031493301341331552586696953063188448...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 10 長い回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
# tests 10
# pass 0
# fail 10
exit_code = 10, reason = DONE
bundle install
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/usr/local/bundle`
mocha --exit -R tap
1..10

#### 入力:
121

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 1 文字長が奇数の回文を求められる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
1221

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 2 文字長が偶数の回文を求められる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
33368088588086

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 3 回文が複数ある場合、最長の回文が出力される
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
12214334

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
43343321

#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 6 比較的長い文字列でも回文が出力できる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 7 自然定数の底から回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 8 単一桁の長い繰り返しから回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 9 長い回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

#### 入力:
439671913169768210880962528779044921214653729760961967312219315729051436700988975291224467598181008351941131051570812459210249369106411836951001002340483417565507341626341463773029280521487959984058684941220744882834172187098695773189403499087280909110119181670989031493301341331552586696953063188448...
#### 標準エラー出力:
main.rb:2:in `initialize': no implicit conversion of Array into String (TypeError)
	from main.rb:2:in `open'
	from main.rb:2:in `main'
	from main.rb:18:in `<main>'

not ok 10 長い回文を見つけられる
  AssertionError: ステータスコードが正常(0)ではありません: expected 1 to equal 0
      at Context.it (test/test_runner.js:45:34)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
# tests 10
# pass 0
# fail 10
exit_code = 10, reason = DONE
bundle install
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/usr/local/bundle`
mocha --exit -R tap
1..10

not ok 1 文字長が奇数の回文を求められる
  AssertionError: 出力すべきデータの個数が違います
  期待された個数: 1
  あなたの個数: 2
  #### 入力:
  121


  #### あなたの答え:
  121
  121

  #### 期待された答え:
  121
  : expected 1 to equal 2
      at Context.it (test/test_runner.js:72:49)
      at <anonymous>

not ok 2 文字長が偶数の回文を求められる
  AssertionError: 出力すべきデータの個数が違います
  期待された個数: 1
  あなたの個数: 2
  #### 入力:
  1221


  #### あなたの答え:
  1221
  1221

  #### 期待された答え:
  1221
  : expected 1 to equal 2
      at Context.it (test/test_runner.js:72:49)
      at <anonymous>

not ok 3 回文が複数ある場合、最長の回文が出力される
  AssertionError: 出力すべきデータの個数が違います
  期待された個数: 1
  あなたの個数: 2
  #### 入力:
  33368088588086


  #### あなたの答え:
  33368088588086
  68088588086

  #### 期待された答え:
  68088588086
  : expected 1 to equal 2
      at Context.it (test/test_runner.js:72:49)
      at <anonymous>

not ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される
  AssertionError: 出力すべきデータの個数が違います
  期待された個数: 1
  あなたの個数: 2
  #### 入力:
  12214334


  #### あなたの答え:
  12214334
  1221

  #### 期待された答え:
  1221
  : expected 1 to equal 2
      at Context.it (test/test_runner.js:72:49)
      at <anonymous>

not ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
  AssertionError: 出力すべきデータの個数が違います
  期待された個数: 1
  あなたの個数: 2
  #### 入力:
  43343321


  #### あなたの答え:
  43343321
  33433

  #### 期待された答え:
  33433
  : expected 1 to equal 2
      at Context.it (test/test_runner.js:72:49)
      at <anonymous>
not ok 6 比較的長い文字列でも回文が出力できる
  Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

#### 入力:
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...
not ok 7 自然定数の底から回文を見つけられる
  Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

#### 入力:
271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...
#### 標準出力:
271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...

not ok 8 単一桁の長い繰り返しから回文を見つけられる
  AssertionError: 出力すべきデータの個数が違います
  期待された個数: 1
  あなたの個数: 2
  #### 入力:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...

  #### あなたの答え:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
  #### 期待された答え:
  111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111...
  : expected 1 to equal 2
      at Context.it (test/test_runner.js:72:49)
      at <anonymous>

not ok 9 長い回文を見つけられる
  AssertionError: 出力すべきデータの個数が違います
  期待された個数: 1
  あなたの個数: 2
  #### 入力:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...

  #### あなたの答え:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
  #### 期待された答え:
  944129555348112446989640880204140883750495206462270137127269885865351490132998118241183800900486023182395584597331741041233202006334563233802566932039484704136961347862173649254687727210853741805804041507643001085928903470682162586846620953273765587127185501771687460757094562030943671123421681327514...
  : expected 1 to equal 2
      at Context.it (test/test_runner.js:72:49)
      at <anonymous>
not ok 10 長い回文を見つけられる
  Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
# tests 10
# pass 0
# fail 10
exit_code = 10, reason = DONE
bundle install
The Gemfile specifies no dependencies
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Bundled gems are installed into `/usr/local/bundle`
mocha --exit -R tap
1..10

ok 1 文字長が奇数の回文を求められる

ok 2 文字長が偶数の回文を求められる

ok 3 回文が複数ある場合、最長の回文が出力される

ok 4 最長の回文が複数ある場合、最初に出現した回文が出力される

ok 5 回文となる領域が重なっている場合にも最長の回文が出力できる
not ok 6 比較的長い文字列でも回文が出力できる
  Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

#### 入力:
123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890...
not ok 7 自然定数の底から回文を見つけられる
  Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

#### 入力:
271828182845904523536028747135266249775724709369995957496696762772407663035354759457138217852516642742746639193200305992181741359662904357290033429526059563073813232862794349076323382988075319525101901157383418793070215408914993488416750924476146066808226480016847741185374234544243710753907774499206...

ok 8 単一桁の長い繰り返しから回文を見つけられる

ok 9 長い回文を見つけられる
not ok 10 長い回文を見つけられる
  Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
# tests 10
# pass 7
# fail 3
exit_code = 3, reason = DONE

command>


最終スコア: 7/10 テストを実行
word, suggestion (occurred 3 times)
